from enum import StrEnum


class ProductStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    REGISTRATION_PENDING = "REGISTRATION_PENDING"
    REGISTERED = "REGISTERED"
    BLOCKED = "BLOCKED"
    REPLACED = "REPLACED"


class RegistrationStatus(StrEnum):
    PENDING = "PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class WarrantyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    REPLACED = "REPLACED"


class AdminRole(StrEnum):
    REVIEWER = "REVIEWER"
    APPROVER = "APPROVER"
    SUPER_ADMIN = "SUPER_ADMIN"


class SerialValidationResult(StrEnum):
    FOUND_UNREGISTERED = "FOUND_UNREGISTERED"
    FOUND_ALREADY_REGISTERED = "FOUND_ALREADY_REGISTERED"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_NOT_AVAILABLE = "VALIDATION_NOT_AVAILABLE"


class ImportRowStatus(StrEnum):
    INSERTED = "INSERTED"
    UPDATED = "UPDATED"
    UNCHANGED = "UNCHANGED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
