name: Publish Pages Legacy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Hide server-only API routes
        run: mv src/app/api src/app/_api

      - name: Build
        run: npm run build
        env:
          PRODUCT_DATA_SOURCE: csv
          STATIC_EXPORT: 'true'
          NEXT_PUBLIC_BASE_PATH: /limac-website
          NEXT_PUBLIC_SITE_URL: https://traicasolutions.github.io/limac-website

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@1ef5a1b1df4c63fe21a2242edbee6cac921ece01 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          enable_jekyll: false

      - name: Output Deployment URL
        run: echo "Deployed to https://traicasolutions.github.io/limac-website/"
